# Generated by Django 6.0.2 on 2026-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=100)),
                ('pickplace', models.CharField(max_length=100)),
                ('picktime', models.TimeField()),
                ('destplace', models.CharField(max_length=100)),
                ('desttime', models.TimeField()),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
