# Generated by Django 6.0.2 on 2026-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gride',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
