# Generated by Django 6.0.2 on 2026-04-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
