# Generated by Django 6.0.2 on 2026-04-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='message',
        ),
    ]
